services:
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_IMAGE_NAME}:${MYSQL_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  gitea:
    container_name: ${GITEA_CONTAINER_NAME}
    image: ${GITEA_IMAGE_NAME}:${GITEA_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_GID}
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=mysql:${MYSQL_PORT}
      - GITEA__database__NAME=${MYSQL_DATABASE}
      - GITEA__database__USER=${MYSQL_USER}
      - GITEA__database__PASSWD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
    depends_on:
      mysql:
        condition: service_healthy

networks:
  default:
    name: ${GITEA_CONTAINER_NAME}_network
    driver: bridge

volumes:
  mysql_data:
    name: ${MYSQL_CONTAINER_NAME}_data
    driver: local
  gitea_data:
    name: ${GITEA_CONTAINER_NAME}_data
    driver: local