version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - default
    volumes:
      - ./data:/var/lib/postgresql/data
      
  app:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - default
    volumes:
      - data:/data
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=db:${DB_PORT}
      - GITEA__database__NAME=${DB_DATABASE}
      - GITEA__database__USER=${DB_USERNAME}
      - GITEA__database__PASSWD=${DB_PASSWORD}
    depends_on:
      - db

networks:
  default:
    name: docker_gitea_network
    driver: bridge

volumes:
  data:
    name: docker_gitea_data
    driver: local