name: ${GLOBAL_NAME}

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  gitea:
    container_name: ${GITEA_CONTAINER_NAME}
    image: ${GITEA_IMAGE_NAME}:${GITEA_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_GID}
      - GITEA__database__DB_TYPE=${GITEA_DATABASE_TYPE}
      - GITEA__database__HOST=${GITEA_DATABASE_HOST}
      - GITEA__database__NAME=${POSTGRES_DATABASE}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_ROOT_PASSWORD}
      - GITEA__server__ROOT_URL=${APP_URL}:${GITEA_HTTP_PORT}
      - TZ=${TIMEZONE}
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - default:/data
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: ${GITEA_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${GITEA_CONTAINER_NAME}_data
    driver: local